### ISSUE TITLE
Toggle feature

### ISSUE THREAD

**Issue by rod-stuchi** [levouh/tint.nvim#14]
Hi @levouh, thanks for the plugin!

Is there a way to toggle the feature?

**Comment by levouh** [comment]
Not at the moment, but I'd be happy to add one here in a bit.

**Comment by levouh** [comment]
Let me know how #15 looks/works for you @rod-stuchi.

**Comment by levouh** [comment]
Merged the above PR, feel free to re-open this issue or create another one if it does not work as expected.

**Comment by rod-stuchi** [comment]
Hi @levouh thank you! That will help a lot!!

if I'm not asking for too much, it will be nice to have a property exposed to know if it is enabled ou disabled, or a toggle function that encapsulate that state.

**Comment by levouh** [comment]
No worries. I'll track this with #18, follow it there.
