### ISSUE TITLE
Tint guisp

### ISSUE THREAD

**Issue by jghauser** [levouh/tint.nvim#24]
At least on my machine, colors defined by `guisp` are left as is (e.g. underline, undercurl ...). Would be nice if those were tinted just as the rest is :)

**Comment by levouh** [comment]
@jghauser can you run:

```lua
print(vim.inspect(vim.api.nvim_get_hl_by_name("...", true))) 
```

where `...` is one of the colors that has `guisp` defined?

~Also, when is this highlight group created relative to when `tint` is loaded?~

I am dumb - we're only tinting foreground and background at the moment. I'll add more keys to tint (or make it configurable). Ignore above.

**Comment by levouh** [comment]
Can you try out #27 @jghauser and let me know how that works? I do not use any highlight groups that define `special`, so it will likely be easier for you to test. If not, let me know and I'll get something going.

**Comment by jghauser** [comment]
Yes, that fixes it! Thanks :)
