### ISSUE TITLE
Disable for diffview

### ISSUE THREAD

**Issue by gegoune** [levouh/tint.nvim#30]
Hi there, not technically an issue but was wondering whether it is possible to disable tinting for diffview's tabpage, I would like to be able to see both sides of diffed files untainted.

Thanks!

**Comment by levouh** [comment]
> Hi there, not technically an issue but was wondering whether it is possible to disable tinting for diffview's tabpage, I would like to be able to see both sides of diffed files untainted.
> 
> Thanks!

`diffview` provides events that you can hook into. I'd set those up, and then `require("tint").disable()` on enter, and `...enable()` on leave.

If there are buffer-specific (or window) settings that `diffview` sets as well (e.g. browse the output of `:let b:` in a buffer (or `:let w:` for window)) then you can also use the `window_ignore_func` to ignore it completely.

Let me know how that works, and if you need help with it.

**Comment by gegoune** [comment]
Ah, of course. I am already turning off gitsigns there, didn't not cross my mind though. Thank you so much! And for that amazing plugin. :)

**Comment by levouh** [comment]
> Ah, of course. I am already turning off gitsigns there, didn't not cross my mind though. Thank you so much! And for that amazing plugin. :)

I have not tested enable/disable much (nor is there a buffer-specific option), so let me know how that works for you and if there are any usability improvements you note.

**Comment by gegoune** [comment]
There is a visual glitch actually which makes `fillchars=diff:╱` filled section (one showing 'previously empty' chunk) blink red. I am not sure, perhaps it has something to do with nightfox or timing of those events, but it seems to work otherwise.
