### ISSUE TITLE
question re `highlight_ignore_pattern`

### ISSUE THREAD

**Issue by jamestrew** [levouh/tint.nvim#31]
I'm a little confused about how the `highlight_ignore_pattern` works. 
> A list of patterns (supplied to `string.find`) for highlight group names to ignore tinting for.

I'm probably misunderstanding this line but I can't seem to get it to work.

### Nvim version
```
NVIM v0.8.0-dev-1166-gf8a1cadcc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
Latest commit as of posting.

### Minimal Config
```lua
-- minimal_config.lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      "levouh/tint.nvim",
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  })
end

_G.load_config = function()
  vim.opt.termguicolors = true
  vim.opt.relativenumber = true
  vim.opt.number = true

  vim.cmd([[hi LineNr guifg=red]])
  vim.cmd([[hi VertSplit guifg=red]])

  require("tint").setup({
    tint = -200, -- exaggerated for effect
    highlight_ignore_pattern = { "WinSeparator", "VertSplit", "LineNr" },
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
  vim.cmd([[autocmd User PackerComplete ++once lua load_config()]])
else
  load_plugins()
  require("packer").sync()
  _G.load_config()
end
```

### Steps to reproduce
1. run `nvim -nu minimal_config.lua minimal_config.lua` (will need a couple attempts for plugins to install and setup correctly)
2. open a few splits
3. navigate between splits

### Expected behavior
The `LineNr` and `WinSeparator`/`VertSplit` highlights maintain un-tinted between navigation of splits

### Actual behavior
Both `LineNr` and `WinSeparator`/`VertSplit` highlights are not ignored and become tinted for splits without focus.

**Comment by levouh** [comment]
`highlight_ignore_pattern` -> `highlight_ignore_patterns`

**Comment by levouh** [comment]
Just did a quick check, but let me know if that is misspelled anywhere @jamestrew. Also, appreciate the detailed issue, regardless of what the actual issue ended up being!

**Comment by jamestrew** [comment]
Yup that was the issue.
So painful when a typo is what's messing you up :sweat_smile: 
Thanks for saving my sanity.

**Comment by levouh** [comment]
> Yup that was the issue.
> So painful when a typo is what's messing you up :sweat_smile: 
> Thanks for saving my sanity.

Happens to the best of us, no worries.
