### ISSUE TITLE
Colorscheme in Demo

### ISSUE THREAD

**Issue by austinliuigi** [levouh/tint.nvim#34]
May I ask what colorscheme you are using in the demo gif?

**Comment by levouh** [comment]
It is my own custom theme that I have locally. Unfortunately I have too much private stuff co-mingled in my own configuration to just make my configuration files repo. public right now, but I will see if I can pull it out and do so.

I've had a similar request with the status-line, so I will hopefully get around to both one day :smile:

**Comment by levouh** [comment]
This is an export of the highlights - I am just using `nvim-highlite` in my own config with tweaks to some of the groups.

[highlights.txt](https://github.com/levouh/tint.nvim/files/10510961/highlights.txt)
