### ISSUE TITLE
Trouble with Heirline Statusline

### ISSUE THREAD

**Issue by joehannes** [levouh/tint.nvim#36]
Hi, awesome plugin!
**Working fine, apart from my statusline.**
If I load the plugin the colors on my heirline.nvim statusline get cleared altogether.
Some few **colors** seem to reappear on special events, most **stay blank.**
I've tried to add "Statusline", "StatusLineNC", "WinBar", "WinBarNC" to the Highlight-Ignore list ... to **no effect.**
Honestly, I've checked the Heirline plugin and am not sure (couldn't find out in reasonable amount of time) what highlight-groups it creates or the names thereof ...
Also, I tried to find in the neovim docs if the Statusline and WinBars actually got separate window ids, but couldn't find out.
**Do you know about that issue, do you have an idea on how to handle it?**
Would be great, because it's looking real good, having one focus on the current window/buffer ...
Cheers, Joehannes

**Comment by levouh** [comment]
The highlight namespaces are created when you load `tint.nvim`, so the namespace will only include highlight groups that are defined when `tint` creates it. This is called out in the [Caveats](https://github.com/levouh/tint.nvim#warning-caveats) for this plugin (some workarounds are discussed there as well).

Generically speaking, I'm not really sure about a better way to handle this as there is no easy way to create "hooks" for when highlights get defined.

Can you start by seeing if any of the workarounds in the link above help? Or change the order in which your plugins are loaded?

>I tried to find in the neovim docs if the Statusline and WinBars actually got separate window ids

I thought the same thing. I would not imagine that the `:h statusline` nor `:h winbar` receive their own highlight namespace, but would be part of the window that they are "tied to" (especially for a `:h winbar`).

**Comment by joehannes** [comment]
hey @levouh :-)

I've give my neovim a break and fled to vscode. for about a week it seemed like back to the future.
finally I found, there's about nothing I can't do in neovim as well, some things are not workingin vscode, plus my mnemonic shortcuts are messed up in vscode-neovim. so that's that, I'm back.

I've plaid around a bit more.
It seems I found a way ... but not a really satisfying solution (yet). Maybe you can help somewhat more if I elaborate:

Calling: `require"tint".refresh()` twice!! does the trick!
Calling it once gets me some colors in my winbar/statusbar, calling it a second time gets me back all my colors.
Thing is, 1st time I can call in a shortcut, aucmd, no problem, but I cannot seem to programmatically call the second invocation effectfully.
Only if I call the second invocation live/per hand from the cmd-line/prompt in nvim, only then do I get back all my colors.

So I tried to work around that with
* `vim.schedule` and
* `vim.defer_fn` ...
but to no avail.

At this point I'm bailing out again.
I made myself a handy global fn and it seems I need to call it everytime I change my theme/background-contrast/start nvim afresh. Ufffhh ... but at least it's something I can do, so I can finally use tint!!

If anything in that rings a bell with you I'd be very pleased to hear about a workaround on how to achieve this second call programmatically/automatically instead ...

Cheers, J

**Comment by joehannes** [comment]
Hey @levouh!

Ok, just now found this to probably be due to neovim entering normal mode in the beginning and some stuff going on there in my aucmds ...
I added bespoke refresh in my aucmd onModeChanged as well - et voila!!! it works now.
So, I don't really know what it boils down to, but anyway, I'm happy now.

Thx for your help and time!!

Cheers, J

**Comment by joehannes** [comment]
Closing this, as it's most probably an issue with my setup. Thx for your time, help and good spirits helping me not give up :-)

Also, summarizing:
* `require"tint".refresh()` put into **all** the right places solved it for me

Cheers, J
