### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by groteck** [levouh/tint.nvim#37]
Hi, thanks for your work is there a way to left the transparent background active?

**Comment by levouh** [comment]
I would give `tint_background_colors` and `highlight_ignore_patterns` a go, and see if that helps at all. The colors for your background would be `Normal` and `NormalNC`.

**Comment by groteck** [comment]
Sorry, I didn't even give you the entire context.
I'm trying using 3 plugins together [catppuccin](https://github.com/catppuccin/nvim), [nvim-transparent](https://github.com/xiyaowong/nvim-transparent) and tint.

After all is fully load if I run the command from **nvim-transparent** `require('transparent').toggle_transparent(true)` (you can see that on the video at the bottom), the all works but once I open the nvim something is not properly set.

I tried as you suggested the `highlight_ignore_patterns` but no luck. I assume that is a fight between the 3 plugins resetting the background of the `NormalNC`.

The configuration:
```lua
--Bottom of my init.lua
-- Colors
vim.t_Co = 256
vim.opt.syntax = 'enable'
vim.opt.colorcolumn = '80'
vim.opt.hlsearch = true
vim.cmd.colorscheme "catppuccin-mocha"
vim.opt.termguicolors = true -- set termguicolors to enable highlight groups

-- Transparent background
vim.g.transparent_enabled = true

--- Catppuccin theme config
require("catppuccin").setup({
    transparent_background = vim.g.transparent_enabled,
    show_end_of_buffer = true, -- show the '~' characters after the end of buffers
    term_colors = true,
    integrations = {
        -- For plugins integrations (https://github.com/catppuccin/nvim#integrations)
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        telescope = true,
        notify = true,
        treesitter = true,
        treesitter_context = true,
        ts_rainbow = true,
        overseer = true,
        illuminate = true,
        neotest = true,
        native_lsp = {
            enabled = true,
            virtual_text = {
                errors = { "italic" },
                hints = { "italic" },
                warnings = { "italic" },
                information = { "italic" },
            },
            underlines = {
                errors = { "underline" },
                hints = { "underline" },
                warnings = { "underline" },
                information = { "underline" },
            },
        },
        indent_blankline = {
            enabled = true,
            colored_indent_levels = true,
        },

    },
})

-- Dim inactive window
require('tint').setup({
    tint_background_colors = false,
    tint = -45, -- Darken colors, use a positive value to brighten
    saturation = 0.5, -- Saturation to preserve
    highlight_ignore_patterns⋅=⋅{⋅"WinSeparator",⋅'NormalNC',⋅'Normal'⋅},
});

-- On window enter retrigger transparent background
vim.api.nvim_create_autocmd({ "WinEnter", "WinLeave", "WinNew", "VimEnter" }, {
    pattern = { "*" },
    callback = function()
        require('transparent').toggle_transparent(true)
    end,
})
```

And this is a video with the behaviour:

https://user-images.githubusercontent.com/833030/215108196-0e80a971-1c16-41e6-815d-2aff4cecf30c.mp4

**Comment by levouh** [comment]
I believe what is happening here is that `nvim-transparent` functions purely off of what is returned by `:highlight`, looking for the groups it has listed and "ensuring" (via various randomly scheduled callbacks) that the `bg` highlight for them is `NONE`.

With the way you have your configuration setup, this is what is happening:

* Load `catppuccin` colorscheme
* Load `tint`, which will save off the tinted version of your color schemes current `Normal` color

Then when you initially split the window, I'm not sure why your autocommand above does not trigger the same thing as `:TransparentEnable`, as this just calls `require("transparent").toggle_transparent(true)` - which is exactly what your autocommand is doing.

Regardless, when you manually call `:TransparentEnable`, it is triggering `doautocmd colorscheme`, which will trigger `tint` to reload its "tinted" namespace and pick up the now transparent background color from `catppuccin` (overridden by `transparent`).

Can you try just calling:

`require('transparent').toggle_transparent(true)` in your configuration _before_ you load `tint`?

**Comment by groteck** [comment]
No idea why but it worked 😄 thanks!!!!!!

**Comment by levouh** [comment]
Let me know if I need to clarify anything, but the reason why is noted in my comment above. TLDR: `tint` pulls from your active colorscheme to determine how to tint things, so you need to make sure your colorscheme is setup correctly (in your case by using `transparent` to set the `bg` highlight attributes to `NONE`) _before_ calling `tint`.

Glad it works.
