### ISSUE TITLE
issue when using with neo-tree float window

### ISSUE THREAD

**Issue by doongjohn** [levouh/tint.nvim#38]
original buffer:
![image](https://user-images.githubusercontent.com/40219740/219897100-87aab79e-a00c-4731-aac9-3f37b0a82d3f.png)

1. open [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) float window using `:NeoTreeFloat`
  ![image](https://user-images.githubusercontent.com/40219740/219896891-ca3afb97-8410-49ca-aafd-14a09af4f70f.png)
2. buffer gets tinted
4. close neo-tree float window by pressing `q`
5. buffer is still tinted
  ![image](https://user-images.githubusercontent.com/40219740/219897021-816f0841-8439-4757-b7e1-46832a549605.png)

**Comment by thesimonho** [comment]
I was just about to post the same issue, but in my case its not a floating window...

start nvim, OK:
![image](https://user-images.githubusercontent.com/5199715/219913448-fbf907f2-553c-425a-a716-c98ae82c2069.png)

toggle neotree with `:Neotree reveal_force_cwd=true toggle=true`:
![image](https://user-images.githubusercontent.com/5199715/219913781-9a7ae71b-5ef7-4764-95c8-8b48597562dd.png)

use the same command to close neotree and the buffer remains tinted:
![image](https://user-images.githubusercontent.com/5199715/219913903-3125e5ef-90ce-43e3-bf67-987099d18d59.png)

if I create a new split and switch buffers a few times the problem seems to go away

configs if useful:

- Tint: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/tint.lua
- Neotree: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/neo-tree.lua

**Comment by levouh** [comment]
I've also seen similar, and it happens with tab movements sometimes as well. Realistically this just means that however a window is being operated on, the way it is closing is not triggering `:h WinEnter` for the destination window after the main window is closed.

I'll take a look to see if I can reproduce it, as well as if there is a simple-ish workaround :+1:

**Comment by doongjohn** [comment]
I think I found a fix...?
![image](https://user-images.githubusercontent.com/40219740/222504006-db82eddd-4745-486d-bac4-f1de36885c0a.png)
this change fixed my issue but I can't confirm this is the actual solution...

**Comment by levouh** [comment]
@doongjohn yes, re-triggering `WinEnter` will fix it (the problem in the first place is that when certain windows are closed, this does _not_ happen - an upstream issue as far as I can tell), but you'd have to do that every time any window is closed forcibly. This isn't something I can handle in the plugin here (at least by that same implementation), and would likely need to be changed upstream, or handled by another means in the plugin here (which I am still [slowly] looking into).

One thing you can do to handle it in a more general sense would be to "override" `vim.api.nvim_win_close`, like:

```lua
local orig = vim.api.nvim_win_close
vim.api.nvim_win_close = function(winid, force)
  orig(winid, force)

  if force then
    vim.schedule(function()
      vim.cmd("doautocmd WinEnter")
    end)
  end
end
```

which obviously has its flaws.

**Comment by akinsho** [comment]
@levouh could this actually just be an issue relating to something that maybe `neo-tree` is doing specifically? I only ever see this issue if I go into a neo-tree window and then leave by toggling the window rather than moving my cursor out. If I move my cursor out manually then this issue doesn't happen. It's almost like the neo tree toggle command does like a `noautocmd` so it purposely doesn't trigger the window autocommand 🤔

**Comment by levouh** [comment]
@akinsho potentially, and at that it would likely be `nui.nvim` rather than `neo-tree.nvim`. But given either case, with the following I actually do not see the issue:

```lua
local opts = {
  plugins = true,
  dir = "/tmp/nvim-test",
}

vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.runtimepath:append(vim.fn.expand(opts.dir))
vim.opt.packpath:append(vim.fn.expand(opts.dir))
vim.opt.termguicolors = true

local function install_packer()
  local install_path = opts.dir .. "/pack/packer/start/packer.nvim"
  if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
  end

  local packer = require("packer")

  packer.init({
    package_root = opts.dir .. "/pack",
    compile_path = opts.dir .. "/plugin/packer_compiled.lua",
  })

  return packer
end

local function chain(funcs)
  local timeout = 1000
  local inc = 1000

  for _, func in ipairs(funcs) do
    vim.defer_fn(func, timeout)
    timeout = timeout + inc
  end
end

local function init()
  chain({
    function()
      vim.cmd("top new | wincmd o")
    end,
    function()
      vim.cmd("Neotree float")
    end,
    function()
      vim.api.nvim_feedkeys("q", "m", true)
    end,
  })
end

local function setup_plugins(packer)
  packer.startup(function(use)
    use("wbthomason/packer.nvim")

    use("MunifTanjim/nui.nvim")
    use("nvim-lua/plenary.nvim")
    use("nvim-tree/nvim-web-devicons")

    use({
      "levouh/tint.nvim",
      config = function()
        require("tint").setup({})
      end,
    })

    use({
      "nvim-neo-tree/neo-tree.nvim",
      config = function()
        require("neo-tree").setup({})
      end,
    })

    vim.api.nvim_create_autocmd({ "User" }, {
      pattern = { "PackerComplete" },
      callback = function()
        init()
      end,
    })

    packer.sync()
  end)
end

local function main()
  if opts.plugins then
    setup_plugins(install_packer())
  end
end

main()
```

when running `nvim -u /tmp/init.lua` (where the above is the content of `/tmp/init.lua`).

**Comment by akinsho** [comment]
@levouh so I'd actually completely forgotten but this issue doesn't happen at all if I *don't lazy load `neo-tree`*. I usually only load it when I run the command to first open the tree.

**Comment by levouh** [comment]
Gotcha, that works. Thanks @akinsho. The only change is to add `cmd = { "Neotree" }` to the configuration of `neo-tree.nvim`, but for the sake of completeness the "minimal reproduction" is now:

```lua
local opts = {
  plugins = true,
  dir = "/tmp/nvim-test",
}

vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.runtimepath:append(vim.fn.expand(opts.dir))
vim.opt.packpath:append(vim.fn.expand(opts.dir))
vim.opt.termguicolors = true

local function install_packer()
  local install_path = opts.dir .. "/pack/packer/start/packer.nvim"
  if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
  end

  local packer = require("packer")

  packer.init({
    package_root = opts.dir .. "/pack",
    compile_path = opts.dir .. "/plugin/packer_compiled.lua",
  })

  return packer
end

local function chain(funcs)
  local timeout = 1000
  local inc = 1000

  for _, func in ipairs(funcs) do
    vim.defer_fn(func, timeout)
    timeout = timeout + inc
  end
end

local function init()
  chain({
    function()
      vim.cmd("top new | wincmd o")
    end,
    function()
      vim.cmd("Neotree float")
    end,
    function()
      vim.api.nvim_create_autocmd({ "WinEnter", "WinClosed" }, {
        group = vim.api.nvim_create_augroup("_tmp", { clear = true }),
        pattern = { "*" },
        callback = function(ev)
          print(string.format("event fired: %s", vim.inspect(ev)))
        end,
      })
    end,
    function()
      vim.api.nvim_feedkeys("q", "m", true)
    end,
  })
end

local function setup_plugins(packer)
  packer.startup(function(use)
    use("wbthomason/packer.nvim")

    use("MunifTanjim/nui.nvim")
    use("nvim-lua/plenary.nvim")
    use("nvim-tree/nvim-web-devicons")

    use({
      "levouh/tint.nvim",
      config = function()
        require("tint").setup({})
      end,
    })

    use({
      "nvim-neo-tree/neo-tree.nvim",
      cmd = { "Neotree" },
      config = function()
        require("neo-tree").setup({})
      end,
    })

    vim.api.nvim_create_autocmd({ "User" }, {
      pattern = { "PackerComplete" },
      callback = function()
        init()
      end,
    })

    packer.sync()
  end)
end

local function main()
  if opts.plugins then
    setup_plugins(install_packer())
  end
end

main()
```

Will try to mess around with the involved plugins to see whats up ASAP. Thanks for the patience all.

**Comment by levouh** [comment]
@sho-87 @akinsho @doongjohn in your experience, does this only happen when closing floating windows?

**Comment by akinsho** [comment]
@levouh I don't use the floating window functionality of neotree at all, so definitely happens even without floats

**Comment by thesimonho** [comment]
same. i have mine docked to the left and use toggle to open/close it. no floats

**Comment by levouh** [comment]
Can you guys give #41 a try and let me know if it works? I have done exactly zero testing with it, so if it fixes the immediate issue, sit on that branch for a bit and let me know if it introduces any other issues.

**Comment by doongjohn** [comment]
https://github.com/levouh/tint.nvim/pull/41 doesn't fix the issue for me.
