### ISSUE TITLE
No tint when nvim opens with splits

### ISSUE THREAD

**Issue by thesimonho** [levouh/tint.nvim#39]
I'm using a session manager to restore my previous session on launch, and it'll sometimes open with multiple splits. Upon opening, the inactive window does not get tinted until I navigate between the splits a few times:

![image](https://user-images.githubusercontent.com/5199715/219915772-d7fb78ff-f68f-44a9-a98c-aa2d901b7f44.png)

This feels somewhat related to the neotree issue (https://github.com/levouh/tint.nvim/issues/38), because the solution in both cases seems to be to navigate between the splits a few times and the tinting will go back to being correct

**Comment by levouh** [comment]
Interesting. I would naively imagine that this would be handled by the delay for `:h VimEnter` that `tint` implements, but it seems that even when using multiple arguments from the command line that this does not work - e.g. `nvim -o foo.lua -o bar.lua`.

Which session manager is it, and do you know if it is just wrapping builtin Vim sessions? Curious if they are doing something weird, or if fixing it for "args" would also fix it for sessions.

**Comment by thesimonho** [comment]
I'm using auto-session: https://github.com/rmagatti/auto-session

It says it makes use of vim's builtin session management but not sure to what extent

**Comment by levouh** [comment]
No worries, I'll try to reproduce it with just `nvim -o ...` and see if whatever fix I come up with also works for you :+1:
