### ISSUE TITLE
question: chaning background color

### ISSUE THREAD

**Issue by gilbh** [levouh/tint.nvim#40]
Hi,

Love this plugin!

How do I define in setup to only change the background color hue (into darker/lighter)? I couldn't figure this one out from:
```
tint_background_colors = true,  -- Tint background portions of highlight groups
```

Thanks!

**Comment by levouh** [comment]
You do not need this plugin if that is what you want to do - see `:h hl-Normal`, `:h hl-NormalNC`, and `:h winhighlight`

**Comment by gilbh** [comment]
Thank you. I will check it out.
