### ISSUE TITLE
question / feature request: explicit highlight overrides

### ISSUE THREAD

**Issue by xero** [levouh/tint.nvim#44]
hello, digging this plugin.
i skimmed through the docs and code and i don’t see this feature anywhere…

is there a way to manually assign a tint color to an object? 
e.g. i’d like to explicitly set the highlight colors for something and let tint do the rest. here’s an example of a function i know doesn’t exist, but explains my goal of setting the Normal mode and Line number background colors:

```
local tint = require("tint").setup({
  tint = -45,
  saturation = 0.9,
  transforms = tint.transforms.SATURATE_TINT,
  tint_background_colors = false,
  highlight_ignore_patterns = { "SignColumn", "LineNr", "WinSeparator", "Status.*" },

  -- something like this???
  highlight_override_patterns = { 
    Normal = { “bg”, tint.colors.clamp(235) },
    LinNr = { “bg”, tint.colors.clamp(232) },
  },
})
```

is there already a way to achieve this? or is this a feature request ;D

**Comment by xero** [comment]
i was sort-of able to achieve this effect by tinting w/a threshold:
```
transforms = {
	require("tint.transforms").tint_with_threshold(-10, "#1a1a1a", 7),
	require("tint.transforms").saturate(0.75),
},
tint_background_colors = true,
highlight_ignore_patterns = { "SignColumn", "LineNr", "CursorLine", "WinSeparator", "Status.*" },
```

![IMG_0029](https://github.com/levouh/tint.nvim/assets/227907/929b5eec-b739-4659-94ef-f46a97d7abd6)


i hate to derail my own thread, but follow up question:
is there a way to call tint when neovim completely loses/gains focus?

edit, nvm i figured that out too…
```
vim.api.nvim_create_autocmd("FocusGained", {
	callback = function()
		tint.untint(vim.api.nvim_get_current_win())
	end,
})
vim.api.nvim_create_autocmd("FocusLost", {
	callback = function()
		tint.tint(vim.api.nvim_get_current_win())
	end,
})
```

**Comment by levouh** [comment]
I don't pay as much attention to issues in this plugin as I should, apologies there @xero. Did you get everything you needed with the tinting threshold then?

`transforms` (see `:h tint-option-transforms`) can be a list of completely custom functions, and one of the arguments for it is the highlight group name itself. So if you want to do something custom for a specific highlight group, you should be able to achieve _precisely_ what you want there. The pre-baked functions like `require("tint.transforms").tint_with_threshold` and `require("tint.transforms").saturate` are obviously limited as covering all "color transform" use cases is difficult/impossible.

**Comment by levouh** [comment]
Closing for now, feel free to re-open.
