### ISSUE TITLE
non colorised code left intact

### ISSUE THREAD

**Issue by rbauduin** [levouh/tint.nvim#45]
I'm trying to use tint.nvim.
It seems that the non colorised code is not tinted.
For example, this code
![image](https://github.com/levouh/tint.nvim/assets/9960888/d5824cc1-2aa1-4121-85b4-0a564687eb97)
it tinted like this:
![image](https://github.com/levouh/tint.nvim/assets/9960888/5f8169ad-9b12-43dc-aef9-323b74069605)
It is even more problematic with a light theme:
![image](https://github.com/levouh/tint.nvim/assets/9960888/7f0aa0f3-afd5-423a-9f30-6f89e6d59043)
becomes
![image](https://github.com/levouh/tint.nvim/assets/9960888/d4efe57c-7cd8-4164-847c-91a1eab71a31)

Not sure if it's due to my setup to write F# code or any other plugin.
But it makes it less useful as there is quite some code not colorised.

**Comment by lbrayner** [comment]
What is your color scheme and what are the contents of `require("tint").setup()` in your configuration?

**Comment by rbauduin** [comment]
I'm using [nvchad](https://nvchad.com/) with themes "onedark" and "gruvbox_light".
My setup is the default:
``` 
{   
       "levouh/tint.nvim",
       event = "WinLeave",
       config = function()
   
                 require("tint").setup({
                 })
       end,
   },
```

**Comment by lbrayner** [comment]
What is the output of `echo &winhighlight`? And `echo getmatches()`? And `autocmd _tint`?

Create a lua file with the following code and source it:

```lua
local hl_groups = {}

for name, ns_id in pairs(vim.api.nvim_get_namespaces()) do
  local highlights = vim.api.nvim_get_hl(ns_id, {})
  if not vim.tbl_isempty(highlights) then
    hl_groups[name] = { ns_id = ns_id, highlights = highlights  }
  end
end

local fd = assert(vim.uv.fs_open("/var/tmp/highlights.txt", "w", 438))
vim.uv.fs_write(fd, vim.inspect(hl_groups))
```

Paste the contents of `/var/tmp/highlights.txt`.

**Comment by rbauduin** [comment]
To run your lua script, I had to upgrade neovim to 0.9.2 (I was on 0.9.0) and it works as expected now.
If you're still interested in the output I can provide it, but for me as this is solved you can close the issue. Thanks for your help!

**Comment by lbrayner** [comment]
@rbauduin great news! :handshake: You can close this.
