### ISSUE TITLE
[Question] Is there any way to disable tint when the current active Windows is a special one?

### ISSUE THREAD

**Issue by tan-wei** [levouh/tint.nvim#49]
For example, now I open `NvimTree` and `Outline` Windows, when one of them is active, the inactive normal buffer should not be tinted.

For now we have these ways to ignore some buffers with `highlight_ignore_patterns` and `window_ignore_function`. But it seems I can't configure tint to behave like the title says.

Thanks!

**Comment by levouh** [comment]
You can use `:h tint-plugin-untint` and `:h tint-plugin-tint` to operate on individual windows, and `:h tint-plugin-enable`/`:h tint-plugin-disable` to control the entire plugin.

You would likely be best off calling these from `window_ignore_function` or via your own set of autocmds.

**Comment by tan-wei** [comment]
OK, I'll try. If I success to configure this, I will leave here my code to help others. Please give me some time to keep this issue open, until I finish it. Thanks!

**Comment by tan-wei** [comment]
Hmm, for me, it works.

For example, I can disable tint when the current window is NvimTree:
```lua
vim.api.nvim_create_autocmd("BufEnter", {
  pattern = { "NvimTree_*" },
  callback = function()
    tint.disable()
  end,
})

vim.api.nvim_create_autocmd("BufLeave", {
  pattern = { "NvimTree_*" },
  callback = function()
    tint.enable()
  end,
})
```

Or I can tint If neovim is not active:
```lua
vim.api.nvim_create_autocmd("FocusGained", {
  pattern = "*",
  callback = function()
    tint.untint(vim.api.nvim_get_current_win())
  end,
})

vim.api.nvim_create_autocmd("FocusLost", {
  pattern = "*",
  callback = function()
    tint.tint(vim.api.nvim_get_current_win())
  end,
})
```
