### ISSUE TITLE
Dim behind popovers?

### ISSUE THREAD

**Issue by lougreenwood** [levouh/tint.nvim#50]
I'm looking for a way to consistently dim the background whenever there is a popover window shown, for example `telescope`, `noice`, `which-key`.

Is it possible that `tint.nvim` can handle this?

Essentially, I would like the contents of the current window behind the popover to receive the same dimming that an in-active window would receive.

Thanks!

**Comment by levouh** [comment]
This should be the default behavior - are you seeing something otherwise?

**Comment by lougreenwood** [comment]
Thanks for the reply. Yes, I'm seeing it, but intermitently, sometimes the tinting is applied to all windows, sometimes if I open a new split in a tabpage and then move to that split window, then the previous window remains un-tinted (as if it's still active).

I need to do some more investigation as I have many plugins and perhaps there is some conflict. I'll update this issue if I find the problem.

Also, for reference, I'm using the Dracula colour scheme.

**Comment by levouh** [comment]
I am going to close this for now @lougreenwood. I am happy to help debug, but tinting behind floating windows is the default behavior and currently works for me. Let me know if you still want to follow up here.
