### ISSUE TITLE
Reducing saturation

### ISSUE THREAD

**Issue by jghauser** [levouh/tint.nvim#8]
Thanks a lot for this plugin! I used to use shade.nvim, and this seems like a much more reliable replacement! :)

What I'm missing from shade.nvim is the ability to not only darken colours but also desaturate them. With my colorscheme darkening alone doesn't really make the inactive window pop out less. Do you think such a feature would be possible with tinit.nvim?

Here's to illustrate what I mean:

Normal:
![20220904_09h32m38s_grim](https://user-images.githubusercontent.com/10319377/188302654-5a6e4223-c722-461b-a430-e144a0b2b14f.jpeg)

Tinted:
![20220904_09h32m25s_grim](https://user-images.githubusercontent.com/10319377/188302669-5ed6a1c3-e391-484e-92b8-e4b77a0a5e27.jpeg)

The second (tinted) one even seems to stand out a little more than the tinted version, making it less obvious which window is in fact the active one.

**Comment by williamboman** [comment]
Ah didn't see there was an issue for this already. I wanted the same so I went ahead and opened #9 for this. Please give it a try and see what you think

**Comment by levouh** [comment]
@jghauser please feel free to re-open this if the change made by @williamboman (thanks again!) does not suffice.

**Comment by jghauser** [comment]
@williamboman thanks a lot! this works perfectly :)
